### ISSUE TITLE
register fails with ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by will-ks** [pushy/pushy-sdk-web#3]
Calling Pushy.register with this code:

```ts
const deviceToken = await Pushy.register({
          appId: '[my-app-id]',
        })
```

results in the following error:
```
Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at pushy-sdk-npm.js:1:1
    at f (pushy-sdk-npm.js:1:1)
    at new i (pushy-sdk-npm.js:1:1)
    at Object.register (pushy-sdk-npm.js:1:1)
    at _callee$ (EnableNotificationsStep.tsx:28:1)
```

**Comment by pushy** [comment]
Closing due to lack of activity.

**Comment by jgarplind** [comment]
This appears to still be an issue.

While the suggested solution* works, I don't think it should be the consumer's concern to install packages that are required to make Pushy work.

*`npm i regenerator-runtime` followed by `import 'regenerator-runtime/runtime'` at the top of the file that uses Pushy

**Comment by pushy** [comment]
Hi @jgarplind,
Thanks for reaching out and for confirming you're still facing this issue.

We've just released version `1.0.15` of the [Pushy Web SDK](https://pushy.me/docs/web-push/get-sdk) which now includes `babel-polyfill` as a dependency of the `npm` package. This should effectively resolve the issue you encountered.

Please install version `1.0.15` of the [Pushy Web SDK](https://github.com/pushy/pushy-sdk-web) from [npm](https://www.npmjs.com/package/pushy-sdk-web) using the following command:
```
npm install pushy-sdk-web@latest --save
```

Please give it a try, and let us know if there's anything else we can help with.

**Comment by pushy** [comment]
Hi @noe-david,
We'd be glad to further assist.

Can you please advise what kind of web framework you're using? Is it React/Angular/Vue or something else?

**Comment by pushy** [comment]
Hi @noe-david,
Thanks for letting us know! We've been able to reproduce and fix the issue in commit https://github.com/pushy/pushy-sdk-web/commit/b0bff868dd93bbb5170ed51a5f87f7ae908a2f45. 

We've just released version `1.0.16` of the [Pushy Web SDK](https://pushy.me/docs/web-push/get-sdk) which directly consumes the Pushy JS module.

Please install version `1.0.16` of the [Pushy Web SDK](https://github.com/pushy/pushy-sdk-web) from [npm](https://www.npmjs.com/package/pushy-sdk-web) using the following command:
```
npm install pushy-sdk-web@latest --save
```

Please give it a try, and let us know if there's anything else we can help with.

**Comment by noe-david** [comment]
Hey again! Thanks for being on this!

I installed the patch and ran the dev server and got this:

```
✘ [ERROR] Could not resolve "promise-polyfill"

    ../node_modules/.pnpm/pushy-sdk-web@1.0.16/node_modules/pushy-sdk-web/src/lib/pushy.js:7:20:
      7 │ import Promise from 'promise-polyfill';
        ╵                     ~~~~~~~~~~~~~~~~~~

  You can mark the path "promise-polyfill" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "whatwg-fetch"

    ../node_modules/.pnpm/pushy-sdk-web@1.0.16/node_modules/pushy-sdk-web/src/util/api.js:1:7:
      1 │ import 'whatwg-fetch';
        ╵        ~~~~~~~~~~~~~~

  You can mark the path "whatwg-fetch" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. 
 ```

**Comment by noe-david** [comment]
Perfect! That solved it 👍 

Thanks for your commitment @pushy team!
