### ISSUE TITLE
ReferenceError: localStorage is not defined in Next.js project

### ISSUE THREAD

**Issue by pepsiamir** [pushy/pushy-sdk-web#6]
I'm wondering why I'm getting this error in the terminal:
```
error - uncaughtException: ReferenceError: localStorage is not defined
    at Object.isRegistered (J:\NodeJs\minifolio\node_modules\pushy-sdk-web\dist\pushy-sdk-npm.js:1:4912)
    at Timeout._onTimeout (J:\NodeJs\minifolio\node_modules\pushy-sdk-web\dist\pushy-sdk-npm.js:1:8859)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by pushy** [comment]
Hi @pepsiamir,
Thanks for reaching out. We'd be glad to assist.

Are you trying to require the `pushy-sdk-web` package inside a Node.js app? Please note that `pushy-sdk-web` is a client-side library used to register website visitors to receive notifications, and can only be used in a browser context.

To send notifications from a Node.js app, please install and make use of our Node.js package [`pushy`](https://www.npmjs.com/package/pushy) instead.
